import unittest

from app.tenant_postgres import (
    POSTGRES_MIGRATIONS,
    CloudSqlPostgresConnectionFactory,
    PostgresConnectionAdapter,
    PostgresTenantStore,
    translate_qmark_parameters,
    validate_postgres_contract,
)
from app.tenant_store import SCHEMA_VERSION


class FakeCursor:
    def __init__(self, connection):
        self.connection = connection
        self.rows = []
        self.description = []
        self.rowcount = 0

    def execute(self, query, parameters):
        normalized = " ".join(query.split())
        self.connection.executed.append((normalized, parameters))
        if normalized.startswith("SELECT version FROM schema_migrations"):
            self.description = [("version",)]
            self.rows = [(version,) for version in self.connection.applied]
        elif normalized.startswith("SELECT to_regclass"):
            self.description = [("table_name",)]
            table = (
                "schema_migrations"
                if self.connection.schema_table_exists
                else None
            )
            self.rows = [(table,)]
        elif normalized.startswith("SELECT COALESCE(MAX(version)"):
            self.description = [("version",)]
            self.rows = [(max(self.connection.applied, default=0),)]
        elif normalized.startswith("INSERT INTO schema_migrations"):
            self.connection.applied.add(int(parameters[0]))
            self.rowcount = 1
        else:
            self.rows = []
            self.rowcount = 1
            if normalized.startswith(
                "CREATE TABLE IF NOT EXISTS schema_migrations"
            ):
                self.connection.schema_table_exists = True
        return self

    def fetchone(self):
        return self.rows[0] if self.rows else None

    def fetchall(self):
        return list(self.rows)

    def __iter__(self):
        return iter(self.rows)


class FakeConnection:
    def __init__(self):
        self.executed = []
        self.applied = set()
        self.schema_table_exists = False
        self.commits = 0
        self.rollbacks = 0
        self.closes = 0

    def cursor(self):
        return FakeCursor(self)

    def commit(self):
        self.commits += 1

    def rollback(self):
        self.rollbacks += 1

    def close(self):
        self.closes += 1


class TenantPostgresTests(unittest.TestCase):
    def test_placeholder_translation_preserves_quoted_question_marks(self):
        query = "SELECT '?' AS literal, value FROM records WHERE id = ?"
        self.assertEqual(
            translate_qmark_parameters(query),
            "SELECT '?' AS literal, value FROM records WHERE id = %s",
        )

    def test_connection_adapter_returns_mapping_rows(self):
        raw = FakeConnection()
        raw.schema_table_exists = True
        adapter = PostgresConnectionAdapter(raw)

        row = adapter.execute(
            "SELECT to_regclass(?) AS table_name",
            ("public.schema_migrations",),
        ).fetchone()

        self.assertEqual(row, {"table_name": "schema_migrations"})
        self.assertIn("%s", raw.executed[0][0])

    def test_postgres_migrations_cover_current_schema(self):
        self.assertEqual(set(POSTGRES_MIGRATIONS), set(range(1, SCHEMA_VERSION + 1)))
        sql = "\n".join(
            statement
            for migration in POSTGRES_MIGRATIONS.values()
            for statement in migration
        )
        for table in (
            "tenants",
            "users",
            "memberships",
            "reports",
            "watchlists",
            "watchlist_items",
            "portfolios",
            "positions",
            "research_tasks",
            "paper_accounts",
            "invitations",
            "audit_events",
            "privacy_requests",
        ):
            self.assertIn(f"CREATE TABLE {table}", sql)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", sql)
        self.assertIn("reject_audit_event_mutation", sql)
        self.assertIn("WHERE status = 'pending'", sql)
        self.assertNotIn("AUTOINCREMENT", sql)
        self.assertNotIn("COLLATE NOCASE", sql)

    def test_offline_contract_audit_passes(self):
        result = validate_postgres_contract()

        self.assertTrue(result["passed"])
        self.assertEqual(result["schema_version"], SCHEMA_VERSION)
        self.assertEqual(result["table_count"], 13)
        self.assertTrue(all(result["checks"].values()))

    def test_migrate_is_serialized_versioned_and_idempotent(self):
        raw = FakeConnection()
        store = PostgresTenantStore(
            lambda: raw,
            clock=lambda: "2026-06-12T12:00:00+00:00",
        )

        self.assertEqual(store.migrate(), SCHEMA_VERSION)
        statement_count = len(raw.executed)
        self.assertEqual(raw.applied, {1, 2, 3})
        self.assertTrue(
            raw.executed[0][0].startswith("SELECT pg_advisory_xact_lock")
        )
        self.assertEqual(store.migrate(), SCHEMA_VERSION)
        second_migration_sql = raw.executed[statement_count:]
        self.assertFalse(
            any(
                query.startswith("CREATE TABLE tenants")
                for query, _ in second_migration_sql
            )
        )

    def test_newer_schema_is_rejected_and_rolled_back(self):
        raw = FakeConnection()
        raw.applied.add(SCHEMA_VERSION + 1)
        store = PostgresTenantStore(lambda: raw)

        with self.assertRaisesRegex(ValueError, "newer"):
            store.migrate()

        self.assertEqual(raw.rollbacks, 1)

    def test_schema_version_handles_uninitialized_database(self):
        raw = FakeConnection()
        store = PostgresTenantStore(lambda: raw)

        self.assertEqual(store.schema_version(), 0)

    def test_cloud_factory_requires_complete_configuration(self):
        with self.assertRaisesRegex(ValueError, "required"):
            CloudSqlPostgresConnectionFactory("", "atlas", "service-account")


if __name__ == "__main__":
    unittest.main()
